// Typing game paragraphs organized by difficulty
export const TYPING_PARAGRAPHS = {
    easy: [
        "The quick brown fox jumps over the lazy dog. This sentence contains all the letters of the English alphabet.",
        "Did you know that the longest word in the English language is pneumonoultramicroscopicsilicovolcanoconiosis? It has 45 letters.",
        "A group of flamingos is called a flamboyance. That sounds like a fun party!",
        "The shortest complete sentence in the English language is 'I am.' That's pretty self-explanatory.",
        "Did you hear about the mathematician who's afraid of negative numbers? He'll stop at nothing to avoid them!"
    ],
    moderate: [
        "Have you ever tried to catch a squirrel? It's harder than it looks. These little critters can climb trees, jump from branch to branch, and scamper across power lines with ease. Speaking of animals, did you know that a group of flamingos is called a flamboyance? That's right, these pink birds really know how to strut their stuff.",
        "How do you make a tissue dance? You put a little boogey in it! If you're in the mood for dancing, you might want to try the cha-cha. This fun and flirty dance originated in Cuba in the 1950s and has been popular ever since. Just be careful not to step on your partner's toes!",
        "Why did the tomato turn red? Because it saw the salad dressing! Speaking of food, have you ever tried durian? This tropical fruit is famous for its pungent smell, which some people describe as similar to rotting onions or sewage. Despite its strong odor, durian is a delicacy in many parts of Southeast Asia.",
        "Did you hear about the kidnapping at the playground? They woke up! Okay, that's a terrible joke. How about this one: Why don't scientists trust atoms? Because they make up everything! Speaking of science, did you know that the largest known dinosaur was the Argentinosaurus, which weighed as much as 10 elephants? That's one big dinosaur!",
        "Why did the tomato turn red? Because it saw the salad dressing! Do you ever wonder how much salad a rabbit can eat in one sitting? It's just a lettuce! And if you ever find yourself lost in a cornfield, don't worry - you'll always find your way out, because corn has ears.",
        "Did you hear about the man who stole a calendar? He got twelve months. But if you think that's bad, have you ever tried to eat a clock? It's very time-consuming. And don't get me started on those who use umbrellas. They always look up in the sky, wondering why the hell the raindrops keep falling on them.",
        "What do you call a bear with no teeth? A gummy bear! But if you think that's bad, have you ever heard of a mouse that can play the piano? It's all about the keys! And if you ever find yourself on a rollercoaster, just remember to scream and enjoy the ride. After all, life is like a rollercoaster - it has its ups and downs, but it's always thrilling."
    ],
    hard: [
        "Why was six afraid of seven? Because seven eight nine! This classic joke always gets a chuckle. Speaking of numbers, did you know that the number zero was invented in India over 1,500 years ago? It took another 500 years for the number zero to be widely used in Europe. Today, zero is an essential part of our number system. Now, if only we could figure out how to divide by zero...",
        "Did you hear about the kidnapping at the playground? They woke up! Okay, that's a terrible joke. How about this one: Why don't scientists trust atoms? Because they make up everything! Speaking of science, did you know that the largest known dinosaur was the Argentinosaurus, which weighed as much as 10 elephants? That's one big dinosaur!",
        "Why did the coffee file a police report? Because it got mugged! But it's not all bad for coffee - it's a great conversation starter. You can always ask someone if they want to grab a cup of coffee, and they'll never say no! And for all the tea lovers out there, did you know that tea is just a hug in a cup?",
        "Why did the chicken cross the playground? To get to the other slide! But watch out for those playground bullies - they always try to swing things their way. And if you ever get a chance to visit a trampoline park, don't be afraid to let loose and jump for joy. Just don't jump into the foam pit, unless you want to get lost in a sea of foam.",
        "What do you call a bear with no teeth? A gummy bear! But if you think that's bad, have you ever heard of a mouse that can play the piano? It's all about the keys! And if you ever find yourself on a rollercoaster, just remember to scream and enjoy the ride. After all, life is like a rollercoaster - it has its ups and downs, but it's always thrilling.",
        "Once upon a time, in a galaxy far, far away, there were 99,999 Coffee-loving aliens who enjoyed playing #arcade games. One day, while playing their favorite game, they discovered a secret code: 8*3+7&5%2=?. Confused but intrigued, the aliens decided to decipher the code. They typed feverishly, but to no avail. After many attempts, they finally figured out the answer: 17! Happy and satisfied, they went back to their coffee and games, until the next mystery code appeared."
    ],
    expert: [
        "Phenomenological hermeneutics, as conceptualized by Gadamer, transcends the Cartesian subject-object dichotomy by emphasizing the historicity of understanding and the fusion of horizons between interpreter and text, thereby revealing the ontological structures that underlie all interpretative endeavors in human consciousness.",
        "The implementation of polymorphic type systems in functional programming languages necessitates sophisticated type inference algorithms that can resolve complex constraint satisfaction problems while maintaining decidability through strategic application of unification techniques and occurs-check mechanisms in lambda calculus representations.",
        "Neuroplasticity encompasses not only synaptic plasticity and neurogenesis but also epigenetic modifications that influence gene expression patterns in response to environmental stimuli, creating dynamic feedback loops between phenotypic adaptation and genomic regulation across multiple temporal scales.",
        "Cryptographic protocols employing elliptic curve discrete logarithm problems provide computational security guarantees under the assumption of bounded polynomial-time adversaries, yet remain vulnerable to quantum algorithms that exploit superposition and entanglement principles for exponential speedup in factorization tasks.",
        "The thermodynamic irreversibility paradox emerges from the apparent contradiction between time-reversible microscopic dynamics governed by Hamiltonian mechanics and macroscopically observed entropy increase in isolated systems, requiring statistical mechanical frameworks to reconcile deterministic chaos with probabilistic emergent behavior."
    ]
};